### ISSUE TITLE
Package issue: `hugo`

### ISSUE THREAD

**Issue by agriyakhetarpal** [piwheels/packages#445]
### Package name

hugo

### Package version

all

### PyPI URL

https://pypi.org/project/hugo

### piwheels URL

https://www.piwheels.org/project/hugo/

### Python version

- [ ] Python 3.7
- [X] Python 3.9
- [X] Python 3.11

### I am aware this is the issue tracker for a Python package index specifically for Raspberry Pi

- [X] Yes

### I have checked for duplicate issues

- [X] Yes

### I am the maintainer

- [X] Yes

### More information

Hi, there! I currently maintain https://github.com/agriyakhetarpal/hugo-python-distributions, which aims to provide `pip`-installable binaries (which are community-enabled and unofficial at this time) for the extended version of the Hugo static site generator for several platforms and architectures, and wanted to expand support for armv7l via piwheels (xref: https://github.com/agriyakhetarpal/hugo-python-distributions/issues/91). The issue with the current broken builds from the source distribution on piwheels is that the package requires some external, non-PyPI dependencies to compile the binary:

1. Golang – _most likely_ armv6l should work from https://go.dev/dl/, since they don't publish armv7l binaries anymore, I'm not sure.
2. Git, for Golang to be able to download and compile the dependencies for the upstream project from GitHub and other code repositories
3. A C compiler, because `CGO_ENABLED` is set to `1` to build the extended version of Hugo. Either Clang or a fairly recent GCC will work. Zig can be used as well, to enable cross-compilation.

Without these, the wheel builds will fail, as they have been doing so currently. Native compilation should be trivial after having access to these, but there might be a few bugs that I would be happy to fix with the packaging infrastructure that I have currently implemented. I don't have access to a CI server for building `armv7l` wheels, but I came here because I can receive help on getting the builds successful plus I'm willing to cooperate by providing a recipe or pre-installation scripts to deal with the above three points. I don't have a Raspberry Pi either right now, so if there is a manylinux equivalent of a Docker image available where one can build with emulation that I can be directed to, that would be great – I'm sure that the package build time won't pass the 3 hour CI time limit in any way; in general, it should not take more than an hour to build via emulation, considering that wheels for aarch64x, s390x, and ppc64le; all pass under 45 minutes. Native compilation takes 3 to 5 minutes without caches being preserved.

**Comment by bennuttall** [comment]
We do have golang and a C compiler available. I think there might be an issue with golang dependencies as we block git access to HTTP(S) for security reasons.

The latest build is failing with:

```
KeyError: 'armv7l'
```

Though I've not looked too closely to what this is.

See https://www.piwheels.org/logs/0000/1179/5137.txt

If there's a way we can build these separately, outside the automated piwheels build procedure, perhaps we can import these wheels.

**Comment by bennuttall** [comment]
```
piwheels@piwheels50:~$ pip3 wheel hugo==0.125.4 --no-deps --extra-index-url https://www.piwheels.org/simple
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting hugo==0.125.4
  Using cached hugo-0.125.4.tar.gz (21 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7450rfeb/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7450rfeb/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-7450rfeb/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 34, in <module>
      KeyError: 'armv7l'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by agriyakhetarpal** [comment]
Thanks for pointing this out, @bennuttall – I think the error is coming from this dictionary in the code:

```
HUGO_ARCH = {
    "x86_64": "amd64",
    "arm64": "arm64",
    "AMD64": "amd64",
    "aarch64": "arm64",
    "x86": "386",
    "s390x": "s390x",
    "ppc64le": "ppc64le",
}[platform.machine()]
```

where I need to add an additional target to build against armhf first to enable building against it, corresponding to the `linux/arm` duo with `GOARM` set to `7`. I can push that and other related changes, and hope for another rebuild!

**Comment by bennuttall** [comment]
Raspberry Pi 1 and Zero are armv6; the others are armv7. If you're on a 32-bit OS (i.e. not aarch64, which piwheels does not support atm), it's armv6 / armhf userland. Generally speaking, our armv6 and armv7 wheels are the same and will work on all Pi models. Otherwise someone could prep an SD card on a Pi 3/4/5 and insert it into a Pi 1/Zero and it wouldn't work.

**Comment by agriyakhetarpal** [comment]
Hi again, @bennuttall! I see that with my recent release (`v0.125.5`) from a few hours ago, this failed with a quite strange error log: https://www.piwheels.org/logs/0000/1183/9026.txt – at the stage where it was installing the build-time dependencies? I can't find any related issue about this in this repository's tracker or that for the main one, so I guess it would be best to tag you here?

**Comment by agriyakhetarpal** [comment]
> I think there might be an issue with golang dependencies as we block git access to HTTP(S) for security reasons.

On another run, I think this note came up with these logs: https://www.piwheels.org/logs/0000/1183/9631.txt `fatal: transport 'https' not allowed` when doing the git clone. Is there a mitigation or a feature flag available to disable this behaviour, since I am not sure if there is a way to not go with the git clone route? ☹️

**Comment by MichaIng** [comment]
Still the same two errors, `OSError: [Errno 28] No space left on device` or failing the Git clone.

@agriyakhetarpal as Git access to HTTPS is strictly blocked, would adding https://github.com/gohugoio/hugo as submodule to https://github.com/agriyakhetarpal/hugo-python-distributions work, a way that it is part of the tarball on PyPI?

**Comment by agriyakhetarpal** [comment]
I think that could work, @MichaIng. I would have two concerns:
- the lack of a Git repository means that the commit information for what appears in `hugo version` cannot be inferred. Homebrew's `hugo version` returns `hugo v0.151.0+extended+withdeploy darwin/arm64`, and `uvx hugo version` returns `hugo v0.151.0-c70ab27ceb841fc9404eab5d2c985ff7595034b7+extended+withdeploy darwin/arm64`; i.e., Homebrew does not contain the commit associated with the build.
- It would bump up the size of the sdist by a bit

I could work with the second point, but will need to find a way to work with the first one.

Thanks!

**Comment by MichaIng** [comment]
@agriyakhetarpal 
Sorry for the late reply. Submodules are loaded like regular Git repositories within a repository, so you can define/freeze the commit, and you can access commit information within just as if you would have cloned it separately.

For the sdist: You can define in pyproject.toml or whatever which files/dirs to include or exclude. You could also clone the subdir only after generating the sdist. But I mean the whole problem here is that cloning the repo at build-time fails (at piwheels), so adding it to the sdist would solve it, and not imply any more download bandwidth overall for users.

**Comment by agriyakhetarpal** [comment]
No worries, thanks for the response! I think I can experiment with submodules; yes. I am also okay with pre-including the submodule in the sdist. I'll get back here if I face any problems.

**Comment by agriyakhetarpal** [comment]
I had switched to a submodule and it has turned out to work just fine. The sdist also includes a limited portion of the submodule's directory structure to keep sizes low. From https://www.piwheels.org/project/hugo, it looks like the package is building fine on Python 3.9 Bullseye and Python 3.13 Trixie, but not on Python 3.11 Bookworm. Unfortunately I don't understand what the logs mean on the 0.161.1 build at https://www.piwheels.org/logs/0000/1644/9601.txt.gz. 

Excerpt from the logs, for ease of access:

```
2026-04-29T21:26:59,693   running build_ext
2026-04-29T21:26:59,741   go: errors parsing go.mod:
2026-04-29T21:26:59,741   /tmp/pip-wheel-r0eorpow/hugo_706b93d644de4dec82ce125a74582613/hugo/go.mod:194: invalid go version '1.25.0': must match format 1.23
2026-04-29T21:26:59,744   Traceback (most recent call last):
2026-04-29T21:26:59,744     File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
2026-04-29T21:26:59,745       main()
2026-04-29T21:26:59,746     File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
2026-04-29T21:26:59,746       json_out['return_val'] = hook(**hook_input['kwargs'])
2026-04-29T21:26:59,747                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-04-29T21:26:59,747     File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
2026-04-29T21:26:59,748       return _build_backend().build_wheel(wheel_directory, config_settings,
2026-04-29T21:26:59,748              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-04-29T21:26:59,749     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 441, in build_wheel
2026-04-29T21:26:59,749       return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
2026-04-29T21:26:59,750              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-04-29T21:26:59,751     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 429, in _build
2026-04-29T21:26:59,751       return self._build_with_temp_dir(
2026-04-29T21:26:59,752              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-04-29T21:26:59,752     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 410, in _build_with_temp_dir
2026-04-29T21:26:59,753       self.run_setup()
2026-04-29T21:26:59,753     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 317, in run_setup
2026-04-29T21:26:59,754       exec(code, locals())
2026-04-29T21:26:59,755     File "<string>", line 624, in <module>
2026-04-29T21:26:59,755     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/__init__.py", line 117, in setup
2026-04-29T21:26:59,756       return distutils.core.setup(**attrs)  # type: ignore[return-value]
2026-04-29T21:26:59,757              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2026-04-29T21:26:59,757     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 186, in setup
2026-04-29T21:26:59,758       return run_commands(dist)
2026-04-29T21:26:59,758              ^^^^^^^^^^^^^^^^^^
2026-04-29T21:26:59,759     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 202, in run_commands
2026-04-29T21:26:59,759       dist.run_commands()
2026-04-29T21:26:59,760     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 1000, in run_commands
2026-04-29T21:26:59,760       self.run_command(cmd)
2026-04-29T21:26:59,761     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 1107, in run_command
2026-04-29T21:26:59,762       super().run_command(command)
2026-04-29T21:26:59,763     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 1019, in run_command
2026-04-29T21:26:59,763       cmd_obj.run()
2026-04-29T21:26:59,764     File "<string>", line 618, in run
2026-04-29T21:26:59,765     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py", line 341, in run_command
2026-04-29T21:26:59,766       self.distribution.run_command(command)
2026-04-29T21:26:59,767     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 1107, in run_command
2026-04-29T21:26:59,767       super().run_command(command)
2026-04-29T21:26:59,768     File "/tmp/pip-build-env-btqdban3/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 1019, in run_command
2026-04-29T21:26:59,769       cmd_obj.run()
2026-04-29T21:26:59,769     File "<string>", line 221, in run
2026-04-29T21:26:59,770     File "<string>", line 393, in _build_hugo
2026-04-29T21:26:59,771     File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
2026-04-29T21:26:59,772       raise CalledProcessError(retcode, cmd)
2026-04-29T21:26:59,773   subprocess.CalledProcessError: Command '['go', 'install', '-trimpath', '-v', '-ldflags', '-s -w -X github.com/gohugoio/hugo/common/hugo.vendorInfo=hugo-python-distributions -X github.com/gohugoio/hugo/common/hugo.buildDate=2026-04-29T13:56:01Z', '-tags', 'extended,withdeploy']' returned non-zero exit status 1.
```

I haven't encountered `invalid go version '1.25.0': must match format 1.23` in my project's CI anywhere before, so I'm kinda stumped by it 😄 I'd appreciate any help!

**Comment by agriyakhetarpal** [comment]
That said, I _think_ this is on piwheels' side, because Go only started accepting the X.Y.Z patch format in Go 1.21. So maybe Golang needs to be bumped on the Bookworm builder if I understand correctly? I am working on some build system changes recently, such as using the Golang compiler available as wheels on PyPI (https://github.com/agriyakhetarpal/hugo-python-distributions/pull/309), which will circumvent this issue entirely if you think updating the Bookworm builder toolset is going to be a more gnarly change than I estimate.

**Comment by MichaIng** [comment]
Makes sense: The builders install the `golang-go` APT package, which is v1.19 on Debian Bookworm:
- https://github.com/piwheels/piwheels/blob/main/deploy_slave_2.sh#L44
- https://packages.debian.org/bookworm/golang-go

EDIT: Wondering how it works on Bullseye with Go 1.15 initially, I see it is downloading Go 1.25 as first step:
```
go: downloading go1.25.0 (linux/arm)
```

IIRC, Go 1.16 was a breaking change regarding how modules were managed, or the Python build backend/script does something different, when facing such an old Go version?

Is the Go version format `X.Y` instead of `X.Y.Z` forwards-compatible? Maybe easiest to keep that, so have more flexibility regarding the initial Go version on the build host. And the patch version should usually not have any breaking change or new/needed feature anyway. I suppose it would just pull the latest patch version then.

**Comment by agriyakhetarpal** [comment]
I shipped a large number of changes for my package, and I think we can declare victory here. https://www.piwheels.org/project/hugo/ is at 0.163.1, which is the latest version of PyPI. To summarise what I changed:
- I ported to the Meson build system with a custom thin wrapper over the meson-python build backend, which I needed to make sure that the platform and ABI tags were of the form `cp3x-none-platform.whl`. I also used PEP 517 hooks to this end to inject the Zig compiler as a dependency only when cross-compiling, as I don't need it for native builds.
- I rely on https://github.com/jmelahman/go-bin, which provides Golang binaries on PyPI as wheels. This project doesn't build them from source unlike how I do it for Hugo and doesn't publish on piwheels, so I added a custom step for piwheels to download the ARM Go toolchain when building: https://github.com/agriyakhetarpal/hugo-python-distributions/pull/322 and discard it when done. I could not find a `PIWHEELS` environment variable or similar to detect this, so the best choice was to use a condition of the form `sys.platform == "linux" and platform.machine() in ("armv6l", "armv7l")`. Another reason for using the Golang compiler from PyPI is https://github.com/gohugoio/hugo/pull/15002, which effectively means that I always need to use the latest Go version, and it's easier to manage my own instead of relying on the system-level Go to be the latest.

With these niceties, the builds seem to be stable enough and work well. There seems to be a slight issue on the Python 3.11 bookworm builder because [PEP 706](https://peps.python.org/pep-0706/) wasn't backported to it (I think?), and I see `TypeError: TarFile.extractall() got an unexpected keyword argument 'filter'`. That is easily fixable, of course. So I can finally use Hugo on my Raspberry Pi that I use for self-hosting :D

**Comment by MichaIng** [comment]
Great!

The `sys.platform == "linux" and platform.machine() in ("armv6l", "armv7l")` condition for manual Go toolchain download is fine anyway, since the issue that PyPI provides no wheels for this platform (and no sdisk) is not limited to piwheels.

The `tarfile` extraction `filter` was added in Python 3.12: https://docs.python.org/3/library/tarfile.html
So makes sense this does not work on Python 3.11. I wonder why does does not cause the Python 3.9 build to fail, is this code section somehow skipped on that Python version? I had this topic on motionEye, where we use `member.isfile()` and `member.name` path checks manually for now.

**Comment by agriyakhetarpal** [comment]
Thanks for all your help!

> The `tarfile` extraction `filter` was added in Python 3.12: [docs.python.org/3/library/tarfile.html](https://docs.python.org/3/library/tarfile.html) So makes sense this does not work on Python 3.11. I wonder why does does not cause the Python 3.9 build to fail, is this code section somehow skipped on that Python version? I had this topic on motionEye, where we use `member.isfile()` and `member.name` path checks manually for now.

Indeed, and I think the reason is the backport. I could not find reliable resources to back this up and do not possess the knowledge of piwheels' internals like you do, and my hunch would be that Debian did backport the 3.12 tarfile extraction filter into previous Python versions, including bullseye Python 3.9 and 3.11, but probably the specific Python 3.11.x version being used by piwheels' bookworm may not have that backport present and needs to be updated. PEP 706 itself was backported upstream to 3.9.17 and 3.11.4+, but that doesn't guarantee Debian's specific bookworm build picked it up at the same time as bullseye's 3.9 build did?

**Comment by MichaIng** [comment]
It was definitely not backported to Debian Bullseye's Python 3.9. That one is Python 3.9.2, was last updated in 2021 (2 years before PIP 706 was introduced), and no mention about it in Debian changelog either: https://metadata.ftp-master.debian.org/changelogs//main/p/python3-defaults/python3-defaults_3.9.2-3_changelog

Debian Bookworm ships Python 3.11.2, too old as well, last update in February 2023, some days after PIP 706 was introduced, but too shortly, and no mention in changelog either: https://metadata.ftp-master.debian.org/changelogs//main/p/python3-defaults/python3-defaults_3.11.2-1_changelog

To be sure, I checked Raspbian (which piwheels uses) and the RPi repository (which ships the kernel etc), but those do not ship any (newer) Python packages either.

<s>Hence, the Python 3.9 build is bypassing that part of the code.</s>

**Comment by MichaIng** [comment]
Ah wait, something went wrong with the log: The Bullseye build log is the same (URL) as the Trixie build log, and shows that Python 3.13 was used. Hence it was not actually the Bullseye build.

This is a "none" ABI package, hence all 3 builds (if they succeed) overwrite each other, and any of them is pulled on any user distro. Not sure whether this causes issues in case of hugo? Usually, if external libraries are used, it does, but in case of Go, that should be fine/self-contained?

But if it uses tarfile extraction filter in runtime, it will fail on Bullseye and Bookworm user platforms anyway.

We discussed the ABI3 and "none" ABI wheel override issue elsewhere:
- https://github.com/piwheels/packages/issues/582#issuecomment-4683102832
- https://github.com/piwheels/piwheels/issues/304

I assume, if tarfile extraction filter is not used in rumtime, the wheel built on Trixie works on all platforms. But there are quirks in some cases, like the tornado issue shows, so best chances are with the wheel built on the oldest platform, i.e. Bullseye. For that, tarfile extraction filter cannot be used.

**Comment by agriyakhetarpal** [comment]
Oh, thanks for the investigation. In this case, yes, things should be fine – the Hugo binary is self-contained indeed. I also run the wheels through a repair step downstream to ensure that is the case, too.

I pushed a fix as of an hour ago in https://github.com/agriyakhetarpal/hugo-python-distributions/commit/621a6d39719facfeef288f87e32f6a2c9e47f31d to not use the filter if it's not available, which should make its way to piwheels whenever the next Hugo release lands and I create a downstream release. All three Pythons should produce the same binary even if overwritten after that. I hope that is correct!

Your presented solution in https://github.com/piwheels/piwheels/issues/304#issuecomment-4682133342 makes sense to me, but the case there is stronger for abi3 wheels – since "none" ABI wheels might have different build steps per Python version for all we know, and abi3 wheels are usually built with more standardised scripts and tooling.

**Comment by MichaIng** [comment]
Great, then all seems fine, ... given that Trixie is stable Debian since soon one year.

It depends a bit on ABI3 vs "none":
- Most "none" wheels I know are pure Python. They define the min Python version in `pyproject.toml`, otherwise it does not matter where the wheel is built.
- ABI3 is for C extensions explicitly, so they do contain C binaries, are often linked against shared libraries, glibc at least, and compiler/linker/header versions can make it incompatible with other distro versions, especially older ones. ABI3 is standardized regarding C extensions and Python versions, but says nothing about platform compatibility. For PyPI, devs/tools solve this via additional platform tags, like `manylinux_x_y`, referring to glibc versions. Otherwise, wheels usually work on newer platforms (than the build system), but often fail on older ones.
- If "none" ABI wheels use Go, which is usually self-contained, no issue. In case of Rust, it is at least usually only glibc, i.e. same as with ABI3 wheels, safe on newer platforms. Otherwise, I did just never face issues with "none" ABI wheels, but there are multiple ABI3-related issues on piwheels. I also don't know which particular wheel(s) https://github.com/piwheels/piwheels/issues/304 is referring to/was originating from. But a solution should be the same for both.

Maybe an easy but unclean solution would be to add fake `manylinux_x_y` tags based on the host platform, which match the glibc version of the platform. So there are always 3 individual wheels. But if there is a platform tag already, like `linux` in case of hugo, and an additional one is just appended like `linux_armv6l.manylinux_2_31_armv6l` (Bullseye) and another `linux_armv6l.manylinux_2_36_armv6l` (Bookworm), I am not sure whether Python resolvers prefer the one with the closer glibc version, as `linux_armv6l` matches everything. Probably better to replace the plain `linux` platform tag only, as this seems to be the only one used where these issues appear: `any` is moreless assured to not contain any platform-dependent binaries, musllinux is usually statically linked, and like manylinux tags contain versioning.

... I reviewed just this case another time: https://www.piwheels.org/project/xgboost/
So it got a manylinux tag, referring to Debian Bookworm, also the logs show it is all the same build from Bookworm. So piwheels seems to decide, maybe because of the "none" ABI, to keep only one wheel, while it should keep all 3 because of the different platform tags. Maybe this is what https://github.com/piwheels/piwheels/issues/304 aims to address actually: not adding some new platform tags, but respecting and differentiating between different platform tags, in case of a "none" ABI. It would not solve simple `linux` tag cases, though.
